#! /usr/bin/env python
#coding=utf-8

# screen consts
SCREEN_WIDTH = 640
SCREEN_HEIGHT = 480

COLOR_WHITE = (255, 255, 255)
COLOR_GRAY = 0x444444

BG_MAX_ALPHA = 50

SMALL_DOT_RADIUS = 10
BIG_DOT_RADIUS = 15

SMALL_PARTICLE = 0
BIG_PARTICLE = 1

GRID_STEP_XY = 40
COLLISION_PARTICLES = 20
SELFEXPLODE_COLLISION_PARTICLES = 100
MAXTIMER = 4000

# hud consts
LIVES_HUD_X = 10
LIVES_HUD_Y = 10

DIRECT_HUD_X_OFFSET = 18
DIRECT_HUD_Y = 15

# keyboard
LEFT_MOUSE_BUTTON = 1

# game consts

# game states
STATE_PLAY = 0
STATE_PAUSED = 1
STATE_GAMEOVER = 2
STATE_MAIN_MENU = 3
STATE_PREPARE = 4
STATE_ENTER_NAME = 5
STATE_CHOOSE_SCORE_TYPE = 6
STATE_SHOW_HIGH_SCORES = 7
STATE_FINISH_CONFIRM = 8
STATE_ABOUT = 9
STATE_CONNECT = 10

# gameplay
SCORE_STEP = 100

DOT_TRAVEL_TIME_MS = 3000
MAX_UPDATE_TIME_MS = 6
BG_CHANGE_TIME_MS = 60000
BG_FADE_TIME_MS = 5000
SCREEN_FLASH_PERIOD = 1000
SURVIVAL_THINK_TIME_MS = 30000
SURVIVAL_TIME_REDUCE_MS = 2000
SURVIVAL_FLASH_TIME = 5000        # how many ms left when screen starts to blink
COLLIDED_DOT_LIVE_TIME = 3000
MAX_VELOCITY_MAGNITUDE = 0.5

GAME_MODE_STANDART = 0
GAME_MODE_SURVIVAL = 1

DIRECT_LEFT = 0
DIRECT_RIGHT = 1
DIRECT_UP = 2
DIRECT_DOWN = 3
DIRECT_COUNT = 4

DIRECT_ANIM_SCALE_TIME = 400

MAX_LIVES = 3
        

# enable debugging
__DEBUG__ = False
